### ISSUE TITLE
Weird bug - Put and Post tests showing up as Get

### ISSUE THREAD

**Issue by pretentiousgit** [rprieto/supersamples#25]
The test for this looks like this:

        it('should update existing metadata', function(done){
            api.put('/api/participant/'+part2._id)
                .set('x-access-token', apiToken2)
                .send({
                    metadata  : [{
                        key   : 'Phone',
                        value : '212-679-4251',
                        group : 'Dental' 
                    },
                    {
                        key   : 'Name',
                        value : 'Shauna',
                        group : 'Dental'
                    }]
                })
                .expect(200)
                .then(function(data){
                    expect(data.body.metadata).to.have.length(6)
                    done();
                })
        })

And it generates the correct CURL but incorrect tagging and styling:
<img width="911" alt="screen shot 2015-08-19 at 4 38 38 pm" src="https://cloud.githubusercontent.com/assets/362722/9368360/cf4a25f8-4690-11e5-9dc1-4d60d7ed664e.png">

The "it" block is nested within two "describe" blocks - the top one to group general objects, the second to group the verb on that object, in this case "participant CRUD" then "participant PUT." This is an occasional bug - it looks like it just turns up sometimes on large suites.

**Comment by rprieto** [comment]
Hi, thanks for the detailed report. Definitely a weird bug! Could you use the JSON renderer and post the corresponding section here?

Trying to figure out if it's a problem with the data model, or in the HTML rendering.

**Comment by pretentiousgit** [comment]
Huh! I cannot - it throws the following error.

``` path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.writeFileSync (fs.js:1103:15)
    at Object.exports.render (/node_modules/supersamples/lib/renderers/json/index.js:13:6)
    at render (/node_modules/supersamples/lib/render.js:62:12)
    at /node_modules/supersamples/lib/render.js:23:5
    at forOwn (/node_modules/supersamples/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/node_modules/supersamples/node_modules/lodash/dist/lodash.js:3303:9)
    at Object.exports.toDisk (/node_modules/supersamples/lib/render.js:22:5)
    at Runner.<anonymous> (/node_modules/supersamples/lib/reporter.js:43:14)
    at Runner.emit (events.js:129:20)
    at /node_modules/mocha/lib/runner.js:619:12
    at /node_modules/mocha/lib/runner.js:548:7
    at next (/node_modules/mocha/lib/runner.js:260:23)
    at Immediate._onImmediate (/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:358:17)```

**Comment by pretentiousgit** [comment]
Looks like it's in the data model - here, from the JSON docs, it thinks the method's a Get.

``` {
    "name": "should update existing metadata",
    "summary": "should update existing metadata",
    "hierarchy": [
      "Participant CRUD tests",
      "Participant PUT",
      "should update existing metadata"
    ],
    "request": {
      "headers": {
        "x-access-token": "ThisIsAToken",
        "content-type": "application/json",
        "content-length": 119
      },
      "method": "GET",
      "path": "/api/participant/",
      "data": {
        "metadata": [
```

**Comment by rprieto** [comment]
That's very odd.... I'll try to reproduce it locally.

**Comment by pretentiousgit** [comment]
Would nesting a test affect it? Like:
    api.put().set().send().then(function(data){
      expect(data.body).this.thing()
      expect(data.body).that.thing()
      api.put().set().send().then(function(data){
          expect(data.body).that.thing()
          done();
      })
    })

**Comment by rprieto** [comment]
Potentially, as `supersamples` only normally expects 1 call per test (otherwise it wouldn't know which one to extract). But your example in the original message didn't have nesting did it?
