### ISSUE TITLE
support for multipart fields?

### ISSUE THREAD

**Issue by gautaz** [rprieto/supersamples#30]
Hello,

One of my test cases is failing with the supersamples reporter, I have isolated the test case that makes supersamples crash:

``` javascript
it('uploads a new sequence', function (done) {
    request(rest).put('/api/sequences')
    .field('name', sequenceTemplate.name)
    .field('entryPoint', sequenceTemplate.entryPoint)
    .field('duration', sequenceTemplate.duration)
    .attach('tarball', tools.sampleTarballPath)
    .expect(200, done);
});
```

When supersamples tries to generate the HTML doc for this test case, it crashes with the following exception:

```
Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at Object.<anonymous> (<project_root>/node_modules/supersamples/lib/renderers/html/handlebars_helper.js:117:19)
    at program13 (eval at <anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:77:130)
    at prog (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/runtime.js:118:12)
    at Object.<anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/base.js:99:23)
    at Object.eval (eval at <anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:154:25)
    at Object.<anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/runtime.js:86:31)
    at Object.sample (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:465:21)
    at Object.invokePartialWrapper [as invokePartial] (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/runtime.js:41:28)
    at program2 (eval at <anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:28:17)
    at prog (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/runtime.js:118:12)
    at Object.<anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/base.js:99:23)
    at program1 (eval at <anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:19:25)
    at prog (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/runtime.js:118:12)
    at Object.<anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/base.js:99:23)
    at Object.eval (eval at <anonymous> (<project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:189:23), <anonymous>:45:25)
    at <project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/runtime.js:86:31
    at <project_root>/node_modules/supersamples/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:465:21
    at writeFile (<project_root>/node_modules/supersamples/lib/renderers/html/index.js:29:17)
    at <project_root>/node_modules/supersamples/lib/renderers/html/index.js:86:5
    at Array.forEach (native)
    at Object.exports.render (<project_root>/node_modules/supersamples/lib/renderers/html/index.js:85:14)
    at render (<project_root>/node_modules/supersamples/lib/render.js:62:12)
    at <project_root>/node_modules/supersamples/lib/render.js:23:5
    at forOwn (<project_root>/node_modules/supersamples/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (<project_root>/node_modules/supersamples/node_modules/lodash/dist/lodash.js:3303:9)
    at Object.exports.toDisk (<project_root>/node_modules/supersamples/lib/render.js:22:5)
    at Runner.<anonymous> (<project_root>/node_modules/supersamples/lib/reporter.js:43:14)
    at emitNone (events.js:72:20)
    at Runner.emit (events.js:166:7)
    at <project_root>/node_modules/mocha/lib/runner.js:735:12
    at <project_root>/node_modules/mocha/lib/runner.js:626:9
    at next (<project_root>/node_modules/mocha/lib/runner.js:283:14)
    at Immediate._onImmediate (<project_root>/node_modules/mocha/lib/runner.js:319:5)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

Does supersamples support multipart requests?

**Comment by taymoor89** [comment]
@gautaz same here, looks like supersamples doesn't support multipart requests.

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
